### ISSUE TITLE
Cannot print in thai language

### ISSUE THREAD

**Issue by KApoNG21** [CXRom/cordova-plugin-rpp#4]
I try to print in Thai language. The result of printer is " ???? ". Please advice me to resolve this problem.

**Comment by CXRom** [comment]
In the manual I found this: 

Support all GB18030 Chinese character,
PC437,Katakana,PC850，PC860,PC863，PC865，WPC1252，PC866，PC852，PC858;
Barcode:CODE39,EAN-13，EAN-8,CODABAR,CODE93,ITF; QR CODE, PDF417.

I dont know if Thai its part of any of the list.
