### ISSUE TITLE
Problem on adding plugin

### ISSUE THREAD

**Issue by SirukakSosta** [CXRom/cordova-plugin-rpp#7]
Hi i have the model Rongta RPP320.
After 2 weeks trying to print through guides and plugins im on absolutely zero.

I was trying to add this plugin add conrdova plugin. But there are errors. Is there a specific version for ionic on this?

Can you help how to import and use <any>window.Rpp?

**Comment by CXRom** [comment]
Well i think the problem is not the version of ionic but if you send more detail please.
